In [1]:
import numpy as np
import pandas as pd

## Questions On Numpy Array

## 1.How to create an empty and a full Numpy array?

In [2]:
#Empty Array
print("-----Empty Array-----")
empty_array_2d = np.empty((3, 4))
print(empty_array_2d)
print("")

#Full Array
print("-----Full Array----")
full_array_2d = np.full((3, 4), 5)
print(full_array_2d)

-----Empty Array-----
[[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.22649121e-307]
 [1.69119330e-306 1.42419802e-306 1.78019082e-306 8.45584427e-307]
 [9.34598247e-307 1.69121231e-306 9.34605037e-307 1.42404727e-306]]

-----Full Array----
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


## 2.Create numpy array filled with all zero.

In [3]:
a = np.zeros([3,3], dtype = int) 
print("Matrix a : \n", a) 

b = np.zeros([5, 3]) 
print("\nMatrix b : \n", b) 

Matrix a : 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

Matrix b : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 3. Create numpy array with filled with all ones.


In [4]:
a = np.ones([3,3], dtype = int)
print("Matrix a: \n", a)

Matrix a: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]


## 4. Checks whether numpy array containes specified row.

In [5]:
a = np.array([[1,2,3],
             [4,5,6],
              [7,8,9]])
print(a)
print([4,5,6] in a.tolist())


[[1 2 3]
 [4 5 6]
 [7 8 9]]
True


## 5. How to remove row in numpy array that contains non-numeric value.

In [6]:
n_arr = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
  
print("Given array:")
print(n_arr)
  
print("\nRemove all rows containing non-numeric elements")
print(n_arr[~np.isnan(n_arr).any(axis=1)])

Given array:
[[10.5 22.5  3.8]
 [41.   nan  nan]]

Remove all rows containing non-numeric elements
[[10.5 22.5  3.8]]


## 6. Remove Single-Dimensional entries from shapes of an array.

In [7]:
x = np.zeros((3, 1, 4))
print(np.squeeze(x).shape)

(3, 4)


## 7. Find the number of occurences of a sequence in numpy array.

In [8]:
arr = np.array([[2, 8, 9, 4], 
                   [9, 4, 9, 4],
                   [4, 5, 9, 7],
                   [2, 9, 4, 3]])
  
# Counting sequence
output = repr(arr).count("9, 4")
  
# view output
print(output)

4


## 8. Find the most frequent value in numpy array.

In [9]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)
  
print("\nMost frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]

Most frequent value in the above array:
1


## 9. Combining a one and two dimensional numpy array.

In [10]:
num_1d = np.arange(5)
print("One dimensional array:")
print(num_1d)
  
num_2d = np.arange(10).reshape(2,5)
print("\nTwo dimensional array:")
print(num_2d)
  
# Combine 1-D and 2-D arrays and display 
# their elements using numpy.nditer() 
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4]

Two dimensional array:
[[0 1 2 3 4]
 [5 6 7 8 9]]
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


## 10. How to build an array of all combinations of two numpy array?

In [11]:
array_1 = np.array([1, 2])
array_2 = np.array([4, 6])
  
print("Array-1")
print(array_1)
  
print("\nArray-2")
print(array_2)
  
comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
  
print("\nCombine array:")
print(comb_array)

Array-1
[1 2]

Array-2
[4 6]

Combine array:
[[1 4]
 [1 6]
 [2 4]
 [2 6]]


# Numpy Array Operation

## Function 1: np.concatenate

In [15]:
#concatenate two array
arr1 = [[1,2],
       [3,4.]]
arr2 = [[5,6,7],
       [8,9,10]]
np.concatenate((arr1,arr2), axis = 1)

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In [16]:
#In this code, we first check the shape of both arrays. 
#Then, if arr1 has fewer columns than arr2, we add zeros to the right of arr1 to make them match in terms of columns. 
#After making the necessary adjustments, we concatenate them along the 0-axis.

arr1 = np.array([[1, 2],
                 [3, 4]])
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10]])

print("Shape of arr1:", arr1.shape)
print("Shape of arr2:", arr2.shape)

rows1, cols1 = arr1.shape
rows2, cols2 = arr2.shape

if cols1 < cols2:
    arr1 = np.column_stack((arr1, np.zeros((rows1, cols2 - cols1))))

result = np.concatenate((arr1, arr2), axis=0)

print(result)

Shape of arr1: (2, 2)
Shape of arr2: (2, 3)
[[ 1.  2.  0.]
 [ 3.  4.  0.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


## Function 2: np.split

In [22]:
# Split an array into multiple sub-arrays.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
subarrays = np.split(arr, [3, 6])
for subarray in subarrays:
    print(subarray)

[1 2 3]
[4 5 6]
[ 7  8  9 10]


In [27]:
#In this modified code, we first check if all the split indices are within the valid range 
#(i.e., less than the length of the array) to ensure that the split is valid. 
#If the indices are valid, we proceed with the split and print the sub-arrays. 
#Otherwise, we print a message indicating that the split indices are invalid.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
split_indices = [3,6]
if all(idx < len(arr) for idx in split_indices):
    subarrays = np.split(arr, split_indices)
    for subarray in subarrays:
        print(subarray)
else:
    print("Invalid split indices")

[1 2 3]
[4 5 6]
[ 7  8  9 10]


## Function 3: np.add

In [28]:
# Addition of two array(working)
# Create two NumPy arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Use np.add to  element-wise addition
result = np.add(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Result of element-wise addition:", result)

Array 1: [1 2 3]
Array 2: [4 5 6]
Result of element-wise addition: [5 7 9]


In [29]:
# Addition of two array(breaking)

# add two NumPy arrays, array1 and array2, that have different shapes. 
# This will result in a "ValueError" because NumPy's np.add function expects arrays to have compatible shapes for element-wise addition.

# To fix this, you can either reshape or pad array2 to have the same shape as `array1. Here's one way to do it:

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5])

if array1.shape[0] > array2.shape[0]:
    padding = array1.shape[0] - array2.shape[0]
    array2 = np.pad(array2, (0, padding), 'constant', constant_values=0)

result = np.add(array1, array2)

print("Array 1:", array1)
print("Array 2:", array2)
print("Result of element-wise addition:", result)

Array 1: [1 2 3]
Array 2: [4 5 0]
Result of element-wise addition: [5 7 3]
